version: '3'

services:
  cache:
    image: redis:alpine
    # Redis may be already installed on your machine, so default redis ports are changed
    expose:
      - 6379


  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  backend:
    build: ./server
    command: >
      bash -c "python manage.py migrate
      && python manage.py makemessages --all -e py,html,jinja
      && python manage.py runserver 0.0.0.0:8535"
    environment:
      - DJANGO_DB_URL=psql://postgres:postgres@db:5432/db
      - DJANGO_CACHE_URL=redis://cache:6379
      - CELERY_BROKER_URL=redis://cache:6379
    ports:
      - 8535:8535
    volumes:
      - .:/code
      - ./server:/code/server
      - pipenv:/code/server/.pipenv

    depends_on:
      - db
      - cache
    links:
      - db:db
      - cache:redis

#  celery:
#    build: ./server
#    command: bash -c "celery -A app worker -l INFO -B"
#    environment:
#      - CELERY_BROKER_URL=redis://cache:6379/1
#      - DJANGO_DB_URL=psql://postgres:postgres@db:5432/postgres
#      - DJANGO_CACHE_URL=redis://cache:6379
#
#    volumes:
#      - .:/code
#      - ./server:/code/server
#      - pipenv:/code/server/.pipenv
#
#    links:
#      - db
#      - cache


volumes:
  postgres_data:
  node_modules:
  pipenv:
