# Generated by Django 2.1 on 2018-09-01 10:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('title', models.CharField(max_length=144, verbose_name='Title')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Body')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('stars', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Stars')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Heading',
                'verbose_name_plural': 'Headings',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Heading', verbose_name='Heading'),
        ),
    ]
