# Generated by Django 2.1 on 2018-09-01 10:39

from django.db import migrations, models
import django.db.models.deletion
import shared.utils.pathrename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='IndexSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('address', models.CharField(max_length=144)),
                ('instagram', models.URLField(default='http://instagram.com/')),
                ('facebook', models.URLField(default='http://facebook.com/')),
                ('vk', models.URLField(default='http://vk.com/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='indexsettings',
            name='phone_numbers',
            field=models.ManyToManyField(to='core.PhoneNumbers'),
        ),
    ]
