# Generated by Django 2.1 on 2018-08-31 14:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import shared.utils.pathrename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('about', ckeditor.fields.RichTextField()),
                ('holidays', ckeditor.fields.RichTextField()),
                ('to_visit', ckeditor.fields.RichTextField()),
                ('customs', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Stars')),
                ('hot', models.BooleanField(choices=[(True, 'Hot'), (False, 'Standard')], verbose_name='Hot')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', ckeditor.fields.RichTextField(default='', verbose_name='Description')),
                ('breakfasts', ckeditor.fields.RichTextField(default='', verbose_name='Breakfasts')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hotel Type',
                'verbose_name_plural': 'Hotel Types',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='IndexSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('address', models.CharField(max_length=144)),
                ('instagram', models.URLField(default='http://instagram.com/')),
                ('facebook', models.URLField(default='http://facebook.com/')),
                ('vk', models.URLField(default='http://vk.com/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('about', ckeditor.fields.RichTextField()),
                ('sights', ckeditor.fields.RichTextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resorts', to='core.Country', verbose_name="Resort's Country")),
            ],
            options={
                'verbose_name': 'Resort',
                'verbose_name_plural': 'Resorts',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_from', models.CharField(max_length=50, verbose_name='Sending from')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='Days duration')),
                ('duration_nights', models.PositiveSmallIntegerField(verbose_name='Night duration')),
                ('cost', models.PositiveIntegerField(verbose_name="Tour's Cost")),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='TourDatePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'verbose_name': 'Tour Datepair',
                'verbose_name_plural': 'Tour Datepairs',
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Tour Type',
                'verbose_name_plural': 'Tour Types',
            },
        ),
        migrations.CreateModel(
            name='TourXcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.BooleanField(choices=[(True, 'Includes'), (False, 'Excludes')], verbose_name='Include/Exclude')),
            ],
            options={
                'verbose_name': 'Tour Xclude',
                'verbose_name_plural': 'Tour Xcludes',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='dates',
            field=models.ManyToManyField(related_name='tours', to='core.TourDatePair', verbose_name="Tour's Date"),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.Hotel', verbose_name="Tour's Hotel"),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.TourType', verbose_name="Tour's Type"),
        ),
        migrations.AddField(
            model_name='tour',
            name='xcludes',
            field=models.ManyToManyField(related_name='tours', to='core.TourXcludes', verbose_name='Tour Includes/Excludes'),
        ),
        migrations.AddField(
            model_name='indexsettings',
            name='phone_numbers',
            field=models.ManyToManyField(to='core.PhoneNumbers'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.Resort', verbose_name="Hotel's Resort"),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.HotelType', verbose_name="Hotel's Type"),
        ),
    ]
