# Generated by Django 2.1 on 2018-09-01 11:05

import ckeditor.fields
from django.db import migrations, models
import shared.utils.pathrename


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SertificateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename, verbose_name='Image')),
                ('title', models.CharField(max_length=144, verbose_name='Title')),
                ('column_1', ckeditor.fields.RichTextField(verbose_name='Column 1')),
                ('column_2', ckeditor.fields.RichTextField(verbose_name='Column 2')),
            ],
            options={
                'verbose_name': 'Certificate Configuration',
            },
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='address',
            field=models.CharField(max_length=144, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='facebook',
            field=models.URLField(default='http://facebook.com/', verbose_name='Facebook.com'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='instagram',
            field=models.URLField(default='http://instagram.com/', verbose_name='Instagram.com'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='location_x',
            field=models.FloatField(default=0.0, verbose_name='Location Z'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='location_y',
            field=models.FloatField(default=0.0, verbose_name='Location Y'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='phone_numbers',
            field=models.ManyToManyField(to='core.PhoneNumbers', verbose_name='Phone Numbers'),
        ),
        migrations.AlterField(
            model_name='indexsettings',
            name='vk',
            field=models.URLField(default='http://vk.com/', verbose_name='vk.com'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Phone Number'),
        ),
    ]
