# Generated by Django 2.1 on 2018-09-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('core', '0002_auto_20180901_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, verbose_name='Full Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('description', models.CharField(max_length=144, verbose_name='Description')),
                ('datetime', models.DateField(verbose_name='Date')),
                ('youtube', models.URLField(verbose_name='YouTube Video URL')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locations.Hotel', verbose_name='Hotel')),
            ],
        ),
    ]
