# Generated by Django 2.1 on 2018-09-01 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
    ]
