# Generated by Django 2.1 on 2018-09-01 15:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video URL'),
        ),
    ]
