# Generated by Django 2.1 on 2018-09-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180901_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexsettings',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='indexsettings',
            name='location_y',
        ),
    ]
