# Generated by Django 2.1 on 2018-09-03 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180902_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='При добавлении текста - отзыв будет помещен в раздел `Текстовые отзывы` ', null=True, verbose_name='Comment'),
        ),
    ]
