# Generated by Django 2.1 on 2018-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180903_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='phonenumbers',
            options={'verbose_name': 'Phone Number', 'verbose_name_plural': 'Phone Numbers'},
        ),
    ]
