# Generated by Django 2.1 on 2018-09-04 12:23

import ckeditor.fields
from django.db import migrations, models
import shared.utils.pathrename


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180903_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename, verbose_name='Image')),
                ('title', models.CharField(max_length=144, verbose_name='Title')),
                ('column1_image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('column1_title', models.CharField(max_length=40)),
                ('column1_body', ckeditor.fields.RichTextField()),
                ('column2_image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('column2_title', models.CharField(max_length=40)),
                ('column2_body', ckeditor.fields.RichTextField()),
                ('column3_image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('column3_title', models.CharField(max_length=40)),
                ('column3_body', ckeditor.fields.RichTextField()),
                ('column4_image', models.ImageField(upload_to=shared.utils.pathrename.path_and_rename)),
                ('column4_title', models.CharField(max_length=40)),
                ('column4_body', ckeditor.fields.RichTextField()),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
