# Generated by Django 2.1 on 2018-09-04 12:34

from django.db import migrations, models
import shared.utils.pathrename


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared.utils.pathrename.path_and_rename),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video')], default=1),
        ),
    ]
