# Generated by Django 2.1 on 2018-09-04 12:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180904_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', ckeditor.fields.RichTextField()),
                ('visa', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
