# Generated by Django 2.1 on 2018-09-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_from', models.CharField(max_length=50, verbose_name='Sending from')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='Days duration')),
                ('duration_nights', models.PositiveSmallIntegerField(verbose_name='Night duration')),
                ('cost', models.PositiveIntegerField(verbose_name="Tour's Cost")),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='TourDatePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'verbose_name': 'Tour Datepair',
                'verbose_name_plural': 'Tour Datepairs',
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Tour Type',
                'verbose_name_plural': 'Tour Types',
            },
        ),
        migrations.CreateModel(
            name='TourXcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.BooleanField(choices=[(True, 'Includes'), (False, 'Excludes')], verbose_name='Include/Exclude')),
            ],
            options={
                'verbose_name': 'Tour Xclude',
                'verbose_name_plural': 'Tour Xcludes',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='dates',
            field=models.ManyToManyField(related_name='tours', to='tours.TourDatePair', verbose_name="Tour's Date"),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='locations.Hotel', verbose_name="Tour's Hotel"),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.TourType', verbose_name="Tour's Type"),
        ),
        migrations.AddField(
            model_name='tour',
            name='xcludes',
            field=models.ManyToManyField(related_name='tours', to='tours.TourXcludes', verbose_name='Tour Includes/Excludes'),
        ),
    ]
