# Generated by Django 2.1 on 2018-09-03 11:33

from django.db import migrations, models
import shared.utils.pathrename


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtype',
            name='preview_image',
            field=models.ImageField(default='', upload_to=shared.utils.pathrename.path_and_rename),
            preserve_default=False,
        ),
    ]
