# Generated by Django 2.1 on 2018-09-03 12:01

from django.db import migrations, models
import shared.utils.pathrename


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourtype_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='tourdatepair',
            name='end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='tourdatepair',
            name='start',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='preview_image',
            field=models.ImageField(upload_to=shared.utils.pathrename.path_and_rename, verbose_name='Preview Image'),
        ),
        migrations.AlterField(
            model_name='tourxcludes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tourxcludes',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
