# Generated by Django 2.1 on 2018-09-03 13:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20180903_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='xcludes',
        ),
        migrations.AddField(
            model_name='tour',
            name='uah_cost',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Tour's Cost"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourXcludes',
        ),
        migrations.AddField(
            model_name='tourincludes',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='tours.Tour'),
        ),
        migrations.AddField(
            model_name='tourexcludes',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludes', to='tours.Tour'),
        ),
    ]
