# Generated by Django 2.1 on 2018-09-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20180903_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='uah_cost',
        ),
        migrations.AddField(
            model_name='tourdatepair',
            name='cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourdatepair',
            name='tour',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.Tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourdatepair',
            name='uah_cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
