# Generated by Django 2.1 on 2018-09-04 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20180903_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourexcludes',
            options={'verbose_name': 'Tour Excludes', 'verbose_name_plural': 'Tour Excludes'},
        ),
        migrations.AlterModelOptions(
            name='tourincludes',
            options={'verbose_name': 'Tour Includes', 'verbose_name_plural': 'Tour Includes'},
        ),
        migrations.AddField(
            model_name='tourdatepair',
            name='currency',
            field=models.CharField(choices=[('d', '$'), ('e', '€'), ('u', '₴')], default='d', max_length=5),
        ),
        migrations.AlterField(
            model_name='tourexcludes',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourincludes',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
