# Generated by Django 2.1 on 2018-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20180904_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdatepair',
            name='hot',
            field=models.BooleanField(choices=[(False, 'Standart'), (True, 'Hot')], default=False),
        ),
    ]
