# Generated by Django 2.1 on 2018-09-04 09:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20180903_1201'),
        ('tours', '0007_tourdatepair_hot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdatepair',
            options={'ordering': ['uah_cost'], 'verbose_name': 'Tour Datepair', 'verbose_name_plural': 'Tour Datepairs'},
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='locations.Country', verbose_name="Tour's Country"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='resort',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', default=2, on_delete=django.db.models.deletion.CASCADE, to='locations.Resort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='resort', chained_model_field='resort', on_delete=django.db.models.deletion.CASCADE, to='locations.Hotel'),
        ),
    ]
